---
# tasks file for config-desktop

- name: Configure users
  include_tasks: user.yml
  tags:
    - users

- name: Configure pacotes
  include_tasks: packages.yml
  tags:
    - packages

- name: Configure git
  include_tasks: git.yml
  tags:
    - git

- name: Configure Ovpn-SERPRO
  include_tasks: ovpn-serpro.yml
  tags:
    - ovpn

- name: Configure OwnClient
  include_tasks: ownclient.yml
  tags:
    - ownclient
