---
# tasks file for config-desktop

- name: Configure users
  include_tasks: user.yml

- name: Install Kazam
  include_tasks: kazam.yml

- name: Configure pacotes
  include_tasks: packages.yml

- name: Configure git
  include_tasks: git.yml

- name: Configure Ovpn-SERPRO
  include_tasks: ovpn-serpro.yml
  
- name: Configure OwnClient
  include_tasks: ownclient.yml
